build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries: []
  library_dirs: []
  undef_macros: []
info:
  github_username: csdms
  plugin_author: Community Surface Dynamics Modeling System
  plugin_license: MIT
  summary: PyMT plugin for the PRMS6 Groundwater component
library:
  entry_point:
  - PRMSGroundwater=bmiprmsgroundwater:bmi_prms_groundwater
  language: fortran
  register: ''
plugin:
  name: prms_groundwater
  requirements:
  - bmi-fortran=2.0
  - prms
  - prms_groundwater
